#!/bin/bash
if [ $# == 3 ]
then
# from string($1) remove everything from the prefix($2) #onwards.
# ppref contains, therefore, everything before the prefix
ppref="${1%${2}*}";
# from string($1) remove everything upto and including the suffix($3)
# ssuff contains, therefore,everything after the suffix
ssuff="${1#*${3}}";
# ppref+prefix($2) contains all characters upto the first #character of the substring we want to extract
# Therefore, remove them. nopref has all characters starting #from the first character of the substring
# we want to extract
nopref="${1#${ppref}${2}}";
#Finally from nopref remove all characters from suffix onwards
echo "${nopref%${3}${ssuff}}";
else
echo "Usage: substr string prefix suffix"
fi